insert into moliya_db.public.student_contracts (
                                                id,
                                                created_at,
                                                created_by,
                                                updated_at,
                                                updated_by,
                                                deleted,
                                                bcn,
                                                academic_year,
                                                guardian_full_name,
                                                guardian_type,
                                                guardianjshshir, language,
                                                address,
                                                amount,
                                                birth_date,
                                                client_type,
                                                comment,
                                                contracted_date,
                                                contract_start_date,
                                                contract_end_date,
                                                gender,
                                                grade,
                                                st_grade,
                                                status,
                                                inactive_date,
                                                passport_id,
                                                passport_issued_by,
                                                phone1,
                                                phone2,
                                                company_id,
                                                student_tariff_id,
                                                student_full_name

)
values (40000,now(),1,now(),1,
        false,'wertyu',2025-2026,'qwertyuio','MOTHER',
        'qwertyutrewrtyu','UZBEK', 'wertyuiop',123456789,
        null,null,null,null,null,null,
        null,null,null,null,null,null,null,null,
        null,1,null,'null,null,null,null,'
        )