CREATE TABLE tariff_change_history
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by          BIGINT,
    updated_by          BIGINT,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    deleted             BOOLEAN,
    student_contract_id BIGINT,
    tariff_status       VARCHAR(255),
    tariff_amount       DOUBLE PRECISION,
    from_date           date,
    to_date             date,
    CONSTRAINT pk_tariffchangehistory PRIMARY KEY (id)
);

ALTER TABLE tariff_change_history
    ADD CONSTRAINT FK_TARIFFCHANGEHISTORY_ON_STUDENT_CONTRACT FOREIGN KEY (student_contract_id) REFERENCES student_contracts (id);